name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - linux-wsl-stable-7.0.12
        version:
          - 7.0.12
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison bc libelf-dev
      - name: Download WSL2 Stable Kernel
        run: |
          git clone --depth 1 --branch ${{ matrix.tag }} https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling.git
      - name: Build WSL2 Stable Kernel
        run: |
          cd WSL2-Linux-Kernel-Rolling
          make -j$(nproc) KCONFIG_CONFIG=../.config
      - name: Upload Kernel Images
        uses: actions/upload-artifact@v7
        with:
          name: bzImage.${{ matrix.version }}
          path: WSL2-Linux-Kernel-Rolling/arch/x86/boot/bzImage
